# Generated by Django 3.0.2 on 2020-03-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_auto_20200306_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='budget',
        ),
    ]
