# Generated by Django 3.0.2 on 2020-03-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0004_auto_20200306_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='user',
        ),
    ]
