# Generated by Django 3.0.3 on 2020-03-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0006_depense_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepensesListes',
            new_name='Budget',
        ),
    ]
